#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use NullDev\Nemesis\Command\GenerateTestsCommand;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

$container = new ContainerBuilder();
$loader    = new YamlFileLoader($container, new FileLocator(__DIR__));
$loader->load('services.yml');

$generateTestCommand = new GenerateTestsCommand();
$generateTestCommand->setContainer($container);

$application = new Application();
$application->add($generateTestCommand);
$application->run();
