#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use NullDev\Nemesis\Command\GenerateTestsCommand;

$application = new Application();
$application->add(new GenerateTestsCommand);
$application->run();
